file            ::= rule+ apply+ EOF

/* Rule */
rule            ::= 'rule' id '(' (id_list)? ')' ('expects' quantifier)? ':' block
quantifier      ::= 
                | number+
                | number+ to_number
                | number+ 'or' 'less' 
                | number+ 'or' 'more'
                | '*'
to_number       ::= 'to' number+ 

/* Statements */
stmt            ::= for_stmt | if_stmt
for_stmt        ::= 
                | 'for' id_list 'in' list ':' block
                | 'for' id for_from for_to for_step? ':' block
for_from        ::= 'from' '-'? number+
for_to          ::= 'to' '-'? number+
for_step        ::= 'step' '-'? number+ 

if_stmt         ::= 'if' disjunction ':' block

/* Logic */
disjunction     ::= disjunction ('or' conjunction)+
conjunction     ::= conjunction ('and' comparison)+

/* Comparison */
comparison      ::= expr comp_expr
comp_expr       ::= ('==' | '!=' | '<' | '>' | '<=' | '>=') expr

/* Arethmitics */
expr            ::= 
                | expr ('+' | '-') term 
                | term
term            ::= 
                | term ('*' | '/') factor
                | factor
factor          ::= ('+' | '-')? ('-'? number+ | '$'? id)

/* Block */
block           ::= NEWLINE INDENT stmt+ DEDENT

/* Apply */
apply           ::= 
                | 'apply' id_params (',' id_params)* 'to' cell_list
                | 'apply' id_params (',' id_params)* 'to' 'all' cell_list_list
                | disjunction
id_params       ::= id '(' (number_list)? ')'

/* Cells */
list            ::= cell_list | cell_list_list
cell_list_list  ::= 
                | '[' cell_list (',' cell_list)? ']'
                | 'ROWS'
                | 'COLUMNS'
                | 'BOXES'
cell_list       ::= 
                | '[' cell (cell_separator cell)* ']'
                | 'CELLS'
cell            ::= 
                | [1-9] ',' [1-9]
                | id
cell_separator  ::= '|' | '->'
cell_value      ::= '$' id

/* Number */
number          ::= [0-9]
number_list     ::= number+ (',' number+)* 

/* Identifier */
id              ::= [\w+]
id_list         ::= id (',' id)*



